# RNG seed, use "" for no seeding
seed: 42

# number of actors
n: 1000

# desired edges correlation; if set to:
#   empty string, an edge correlation step is omitted,
#   value in <0.0;1.0>, all pairwise correlations between layers will be adjusted to the given value
#   filename with .csv extension, correlation matrix will be loaded from a specified file
edges_cor: scripts/configs/example_generate/edges_cor.csv

# file with parameters for each layer
layer_params: scripts/configs/example_generate/layer_params.csv

# maximum number of iterations for sampling degrees
d_max_iter: 1000

# maximum number of iterations for sampling cluster sizes
c_max_iter: 1000

# number of batches for edge rewiring
t: 100

# percentage of edges to be rewired in each rewiring batch
eps: 0.01

# dimensionality of latent space
d: 2

# name of file for output edges
edges_filename: edges.dat

# name of file for output communities
communities_filename: communities.dat
